driver:
  name: docker
  use_sudo: false
  privileged: true
  forward:
    - 80
transport:
  name: sftp
platforms:
  - name: centos
    driver_config:
      run_command: /usr/lib/systemd/systemd
suites:
  - name: nitrogen
    provisioner:
      salt_bootstrap_options: -X -p git stable 2017.7
  - name: carbon
    provisioner:
      salt_bootstrap_options: -X -p git stable 2016.11
verifier:
  name: shell
  remote_exec: false
  command: pytest -v tests/integration/

